name: roundabnt
description: This package allows users to round numbers using Brazilian ABNT rules (NBR 5891).
version: 1.0.5+0
homepage: https://github.com/sergiotucano/roundabnt

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^6.0.0
