name: roundabnt
description: Round number with brazilian abnt rule
version: 0.0.1+1
homepage: https://github.com/sergiotucano/roundabnt

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
